
language: ruby
rvm:
  - 2.4.1

before_script:
  - chmod +x ./script/cibuild

install: gem install jekyll html-proofer
script: ./script/cibuild

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

cache: bundler

notifications:
  email: false

exclude: [vendor]
